### ISSUE TITLE
Reading huge files

### ISSUE THREAD

**Issue by falko100** [MuellerConstantin/PyQvd#4] opened 2024-09-03 19:03 UTC
I have QVD file of 900mb and it wont read it or takes too long.
Is there any way to show a progress bar while reading the file?
Or at least some sort of indicator?

**Comment by MuellerConstantin** [comment] 2024-09-04 09:16
**Short Answer:**

Of course this library has its limitations in terms of data size. It should be obvious that this library cannot deliver the same performance as a Qlik Sense installation when reading the data. 900mb is a lot, I assume we are talking about several tens of millions of rows, right?

**Long Answer:**

On the other hand, if you're reading large files it makes sense to track the progress, I agree with you there. One could think about a mechanism similar to `pandas`. `pandas` offers the option to read large files chunk by chunk and between reading the chunks you could update a progress bar with `tqdm` for example.

The problem is the way QVD stores its data. In a QVD file the data isn't stored in a plain tabular format like in a CSV. The cell values are stored in a separate table (_Symbol Table_) and the actual rows (_Index Table_) only contains value indices, hence must be decoded. So you would have to read the entire _Symbol Table_ at the beginning in order to be able to decode the rows. The individual rows (_Index Table_) could then be read in chunks, similar to `pandas`. So if the problem with the large QVD file is that there are too many rows, then reading chunks helps. However, if the size is (also) due to too many cell values, this approach is only of limited help because the entire symbol table has to be read in at the beginning for decoding anyway.

So what's the shape of your 900mb QVD file? Are there so many rows? I have to check for a way to integrate chunking into the existing major version API. Any suggestions?

**Comment by falko100** [comment] 2024-09-05 07:35
I don't have Qlik myself, these files are supplied by my client.
Indeed they are very big, even Sublime Text has trouble opening the csv after conversion.
A slightly bigger .qvd managed to get read and written to a csv. This one has 5.310.170 rows.

Functionally I'd probably like to see a reader that has a pointer-based system so you can trigger reading one or many lines and handle those before the next lines are read. If you add a total amount of rows and current position of the pointer people are free to add their own progress bars.

**Comment by MuellerConstantin** [comment] 2024-09-10 07:07
Sounds like a similar solution like the `pandas` [way](http://pandas.pydata.org/pandas-docs/stable/user_guide/io.html#iterating-through-files-chunk-by-chunk). We have to introduce an additional option for specifying the chunk/iteration size:

```python
from pyqvd import QvdTable

itr = QvdTable.from_qvd("path/to/file.qvd", chunksize=100)

for chunk in itr:
    ...
```

To implement this we would need a class analogous to pandas [TextFileReader](https://github.com/pandas-dev/pandas/blob/715585de0d66383c51ce290ad6b18a036254d007/pandas/io/parsers/readers.py#L1140) class, which acts as an iterator and in this case is returned instead of the `QvdTable`.

**Comment by MuellerConstantin** [comment] 2024-10-05 09:51
I just published a [pre-release](https://pypi.org/project/PyQvd/2.2.0a1/) of a new major version, that contains support for reading QVD files in chunks. This would allow you to display a progress bar, using `tqdm` for example. See the [documentation](https://pyqvd.readthedocs.io/v2.2.0-alpha.1/) for details. @falko100 Feel free to check it out and give me some feedback if you want.

**Comment by msimmoteit-neozo** [comment] 2024-10-07 13:36
@falko100 Otherwise if it's a performance issue, maybe you can profile your program when reading in big files and share the profile information.
Understanding which lines of code take the most time would help in optimizing

**Comment by MuellerConstantin** [comment] 2024-12-04 20:37
This issue is addressed in the (latest version)[https://pypi.org/project/PyQvd/2.2.0/] by introducing a feature for reading QVD files by chunks.

**Closed by MuellerConstantin** 2024-12-04 20:37 UTC
Labels: bug, enhancement
